#!/usr/bin/env python3
"""Regenerate a lore's index from wiki/ frontmatter.

The only writer of <lore>/index.md and <lore>/index/<Group>.md. Part of the
lore plugin contract (skills/lore/SKILL.md, "Index regeneration"). Stdlib only.

Usage: lore_index.py <lore> [--split | --flat] [--groups] [--seed-groups] [--check]

Exit codes: 0 done (WARN:/NOTE: lines may be on stdout), 1 refusal or drift,
2 usage error or <lore> is not a lore (needs wiki/ and CLAUDE.md).
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

MARKER = ("<!-- generated by lore_index.py from wiki/ frontmatter — do not edit; "
          "set group:/description: in the page and re-run -->")
UNGROUPED = "Ungrouped"
DEPRECATED = "Deprecated"
ENTRY_CAP = 200          # every entry and hub line must be shorter than this
SPLIT_THRESHOLD = 200    # more entries than this -> NOTE suggesting --split
SCALAR_FIELDS = ("title", "description", "group", "status")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---(?:\n|\Z)", re.DOTALL)
INDEX_ENTRY_RE = re.compile(r"^- \[(?P<title>[^\]]+)\]\((?P<target>[^)]+)\)")
INDEX_HEADING_RE = re.compile(r"^##\s+(?P<heading>.+?)\s*$")


def scalar(value):
    """One frontmatter scalar: quotes stripped, trailing ` #comment` dropped."""
    value = value.strip()
    if value[:1] in ("'", '"'):
        end = value.find(value[0], 1)
        return value[1:end] if end != -1 else value[1:]
    cut = value.find(" #")
    return value[:cut].rstrip() if cut != -1 else value


def read_scalars(text):
    """The top-level SCALAR_FIELDS of a page's frontmatter, or None without one.

    Indented (nested) lines are ignored; a key whose value is a nested block
    reads as absent.
    """
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    fields = {}
    for line in match.group(1).split("\n"):
        if not line or line[0].isspace() or line.startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if sep and key.strip() in SCALAR_FIELDS and scalar(value):
            fields[key.strip()] = scalar(value)
    return fields


def load_entries(lore):
    """One entry per wiki/*.md (sorted by filename) plus the WARN lines raised.

    A page is never dropped: without frontmatter or a title it is listed from
    its filename, with an empty hook and no group.
    """
    entries, warnings = [], []
    for path in sorted((Path(lore) / "wiki").glob("*.md")):
        try:
            fields = read_scalars(path.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            fields = None
        if fields is None or not fields.get("title"):
            warnings.append(f"WARN: no frontmatter wiki/{path.name}")
            fields = fields or {}
        entries.append({
            "file": f"wiki/{path.name}",
            "title": fields.get("title") or path.stem.replace("_", " "),
            "hook": fields.get("description", ""),
            "group": fields.get("group"),
            "deprecated": fields.get("status") == "deprecated",
        })
    return entries, warnings


def heading_for(entry):
    if entry["deprecated"]:
        return DEPRECATED
    return entry["group"] or UNGROUPED


def group_entries(entries):
    """Ordered (heading, entries) pairs: headings case-insensitively, then
    Ungrouped, then Deprecated; entries by title, case-insensitively."""
    buckets = {}
    for entry in entries:
        buckets.setdefault(heading_for(entry), []).append(entry)
    ordinary = sorted((h for h in buckets if h not in (UNGROUPED, DEPRECATED)), key=str.casefold)
    special = [h for h in (UNGROUPED, DEPRECATED) if h in buckets]
    return [(h, sorted(buckets[h], key=lambda e: e["title"].casefold())) for h in ordinary + special]


def list_groups(entries):
    """(group, count) by the pages' own group value — deprecated pages count
    too, so the agent sees every group that exists. Ordered the same way
    group_entries orders headings (case-insensitively, then Ungrouped, then
    Deprecated last) so a page whose frontmatter literally sets
    group: Deprecated sorts where it renders, not alphabetically among the
    ordinary groups."""
    counts = {}
    for entry in entries:
        name = entry["group"] or UNGROUPED
        counts[name] = counts.get(name, 0) + 1
    ordinary = sorted((g for g in counts if g not in (UNGROUPED, DEPRECATED)), key=str.casefold)
    special = [g for g in (UNGROUPED, DEPRECATED) if g in counts]
    return [(g, counts[g]) for g in ordinary + special]


def entry_line(entry):
    """The index line for an entry, and the WARN raised when it had to be cut."""
    prefix = f"- [{entry['title']}]({entry['file']})"
    line = f"{prefix} — {entry['hook']}" if entry["hook"] else prefix
    if len(line) < ENTRY_CAP:
        return line, None
    warning = f"WARN: over-cap {entry['file']} ({len(line)} chars)"
    budget = ENTRY_CAP - 1 - len(prefix) - len(" — ") - len("…")
    if budget >= 0:
        hook = entry["hook"][:budget]
        if " " in hook:
            hook = hook.rsplit(" ", 1)[0]
        cut = f"{prefix} — {hook}…" if hook else prefix
        return cut, warning
    # The title+link prefix alone is already too long to fit any hook. Cut
    # the title instead, at a word boundary, same "…" convention as above.
    # Never cut the link target: a truncated path is a dead link, which is
    # worse than a long line — so if even an empty title can't fit under
    # the cap because the file path itself is too long, emit the line as-is.
    overhead = len(f"- [{''}…]({entry['file']})")
    title_budget = ENTRY_CAP - 1 - overhead
    if title_budget <= 0:
        return line, warning
    title = entry["title"][:title_budget]
    if " " in title:
        title = title.rsplit(" ", 1)[0]
    if not title:
        return line, warning
    return f"- [{title}…]({entry['file']})", warning


def render_flat(entries):
    lines, warnings = ["# Lore Index", MARKER], []
    for heading, members in group_entries(entries):
        lines += ["", f"## {heading}"]
        for entry in members:
            line, warning = entry_line(entry)
            lines.append(line)
            if warning:
                warnings.append(warning)
    return "\n".join(lines) + "\n", warnings


def group_filename(heading):
    return heading.replace(" ", "_").replace("/", "_") + ".md"


def hub_line(heading, members, filename=None):
    """`- [Group](index/Group.md) — <n> pages: <titles>` cut under the cap at a
    title boundary; `, …` marks the cut.

    filename overrides the computed index/<Group>.md target — render_split
    passes this when group_filename(heading) collided with an earlier
    heading and this heading was written under a disambiguated name.

    The link target is never truncated. If the heading/filename alone leave
    no room even for a bare "…" under the cap, the full, uncut line is
    emitted instead — cutting titles wouldn't bring it under the cap either,
    so there is nothing to gain from hiding them (same precedent as
    entry_line's pathological long-filename case).
    """
    filename = filename or group_filename(heading)
    n = len(members)
    base = f"- [{heading}](index/{filename}) — {n} page{'s' if n != 1 else ''}: "
    titles = [entry["title"] for entry in members]
    naive = base + ", ".join(titles)
    if len(base + "…") >= ENTRY_CAP:
        return naive
    chosen = []
    for title in titles:
        last = len(chosen) + 1 == len(titles)
        candidate = base + ", ".join(chosen + [title]) + ("" if last else ", …")
        if len(candidate) >= ENTRY_CAP:
            break
        chosen.append(title)
    if len(chosen) == len(titles):
        return naive
    return base + ", ".join(chosen) + (", …" if chosen else "…")


def render_split(entries):
    """A hub index.md plus one index/<Group>.md per heading.

    Two headings can map to the same group_filename() (e.g. "Power/Thermal"
    and "Power Thermal" both become Power_Thermal.md). Losing a whole
    group's page listing to a silent overwrite would violate "every page
    stays reachable", so headings are claimed in order (group_entries'
    order) and a later collision is disambiguated with a _2, _3, … suffix
    before .md, with a WARN so the groups get renamed.
    """
    files, warnings = {}, []
    hub = ["# Lore Index", MARKER, ""]
    claimed = set()
    for heading, members in group_entries(entries):
        filename = group_filename(heading)
        if filename in claimed:
            stem = filename[:-len(".md")]
            n = 2
            while f"{stem}_{n}.md" in claimed:
                n += 1
            filename = f"{stem}_{n}.md"
            warnings.append(f'WARN: group filename collision; "{heading}" written as index/{filename}')
        claimed.add(filename)
        hub.append(hub_line(heading, members, filename))
        lines = [f"# {heading}", MARKER, ""]
        for entry in members:
            line, warning = entry_line(entry)
            lines.append(line)
            if warning:
                warnings.append(warning)
        files[f"index/{filename}"] = "\n".join(lines) + "\n"
    files["index.md"] = "\n".join(hub) + "\n"
    return files, warnings


def render(lore, split=None):
    """{relative path: text} for the index files, plus the WARN/NOTE lines.

    split=None reads the current mode from disk (index/ exists → split). The
    dashboard calls this to detect drift; the CLI writes what it returns.
    """
    lore = Path(lore)
    if split is None:
        split = (lore / "index").is_dir()
    entries, messages = load_entries(lore)
    if split:
        files, warnings = render_split(entries)
    else:
        text, warnings = render_flat(entries)
        files = {"index.md": text}
        if len(entries) > SPLIT_THRESHOLD:
            warnings.append(f"NOTE: {len(entries)} entries > {SPLIT_THRESHOLD}; run with --split to split the index")
    return files, messages + warnings


def write_files(lore, files, split=False):
    """Write every rendered file. While split, the script owns index/
    entirely: it (re)creates the directory and removes any index/*.md that
    no longer corresponds to a heading — keyed off split explicitly, not
    inferred from files, since a wiki/ that has emptied out renders zero
    headings (files has no "index/" key at all) yet index/ must still be
    cleared out and kept, not left with stale group files or deleted."""
    lore = Path(lore)
    for rel, text in files.items():
        (lore / rel).parent.mkdir(exist_ok=True)
        (lore / rel).write_text(text, encoding="utf-8")
    if split:
        (lore / "index").mkdir(exist_ok=True)
        for stale in (lore / "index").glob("*.md"):
            if f"index/{stale.name}" not in files:
                stale.unlink()


def check(lore):
    """Relative paths whose on-disk content differs from a fresh render —
    missing files and stale index/*.md files included. Sorted."""
    lore = Path(lore)
    files, _ = render(lore)
    drift = []
    for rel, text in files.items():
        try:
            current = (lore / rel).read_text(encoding="utf-8")
        except OSError:
            current = None
        if current != text:
            drift.append(rel)
    if (lore / "index").is_dir():
        for stale in (lore / "index").glob("*.md"):
            if f"index/{stale.name}" not in files:
                drift.append(f"index/{stale.name}")
    return sorted(drift)


def in_folder(target, folder):
    """True only for `<folder>/<name>.md` — one path component directly under
    folder, no traversal. An index link is hand-written text that may point
    anywhere, so every path the script reads or writes from one is filtered
    through this: pages live in `wiki/`, group files in `index/`, and
    `index/../../x.md` is neither."""
    head, sep, name = target.partition("/")
    return bool(sep) and head == folder and name.endswith(".md") and "/" not in name


def _read(path):
    try:
        return Path(path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def read_current_index(lore):
    """(heading, target) for every entry line of the index on disk, following
    hub lines into index/<Group>.md (the hub link text is that heading), and
    whether index.md carries the generated marker.

    Hub lines are followed one level only — out of index.md into a group
    file, never out of a group file — so a hand-written index whose group
    file links back to itself is read once instead of recursing forever; a
    hub line inside a group file is kept as an ordinary entry. Only a real
    `index/<name>.md` is followed (in_folder), so a link that escapes the
    lore is never opened."""
    lore = Path(lore)
    text = _read(lore / "index.md")
    pairs = []

    def walk(body, heading, follow):
        for line in body.split("\n"):
            found = INDEX_HEADING_RE.match(line)
            if found:
                heading = found.group("heading")
                continue
            entry = INDEX_ENTRY_RE.match(line)
            if not entry:
                continue
            target = entry.group("target").strip()
            if follow and in_folder(target, "index"):
                walk(_read(lore / target), entry.group("title").strip(), False)
            else:
                pairs.append((heading, target))

    walk(text, None, True)
    return pairs, MARKER in text


def is_curated(lore, entries):
    """True when regenerating would lose hand-made curation, i.e. index.md
    carries no generated marker and lists at least one page under a real
    topic heading that the page's own `group:` would not reproduce —
    exactly what --seed-groups has to read before it is overwritten.

    The question is per entry, not per lore: a v0.4 index keeps its curation
    while any one of its headings is still carried only by the index, so
    pages arriving already grouped (v0.5 ingest writes `group:` on every new
    page) cannot switch the guard off underneath the pages that predate them.
    Everything a plain regeneration reproduces is not curation: the marker
    (a generated index, however it was later touched), `## Ungrouped` and
    `## Deprecated` headings, a missing index, and any entry whose page
    already carries a group — which is why a lore that --seed-groups has
    migrated passes even if a human strips the marker line."""
    pairs, generated = read_current_index(lore)
    if generated:
        return False
    grouped = {entry["file"] for entry in entries if entry["group"]}
    return any(heading not in (None, UNGROUPED, DEPRECATED) and target not in grouped
               for heading, target in pairs)


def _after_value(lines, start):
    """Index right after the (possibly multi-line block-scalar) value that
    begins at lines[start], so a new top-level key can be inserted there
    without splitting a `description: |`/`title: >` block apart. A
    continuation line begins with whitespace; a blank line still counts as
    part of the block when a later indented line follows before the next
    top-level key. For an ordinary single-line value this is just start + 1,
    same as before."""
    i = start
    while i + 1 < len(lines):
        nxt = lines[i + 1]
        if nxt and nxt[0].isspace():
            i += 1
            continue
        if not nxt:
            j = i + 2
            while j < len(lines) and not lines[j]:
                j += 1
            if j < len(lines) and lines[j] and lines[j][0].isspace():
                i += 1
                continue
        break
    return i + 1


def seed_groups(lore):
    """Stamp `group: <heading>` (after description:, else after title:) into
    every indexed page that has frontmatter and no group. Deprecated-section
    entries are skipped. Returns the (target, heading) pairs stamped.

    This is the only code here that writes to a page, from targets taken out
    of a hand-written index, so a target that is not a `wiki/<name>.md` of
    this lore is skipped outright (in_folder): a link such as
    `../elsewhere/notes.md` is somebody else's file, never stamped.

    The insertion point is placed after the anchor's full value, including
    any block-scalar continuation lines, so a multi-line description: | or
    title: > is never split apart."""
    lore = Path(lore)
    stamped, seen = [], set()
    pairs, _ = read_current_index(lore)
    for heading, target in pairs:
        if heading in (None, UNGROUPED, DEPRECATED) or target in seen or not in_folder(target, "wiki"):
            continue
        path = lore / target
        if not path.is_file():
            continue
        seen.add(target)
        text = path.read_text(encoding="utf-8", errors="replace")
        fields = read_scalars(text)
        if fields is None or fields.get("group"):
            continue
        match = FRONTMATTER_RE.match(text)
        lines = match.group(1).split("\n")
        description = next((i for i, l in enumerate(lines) if l.startswith("description:")), None)
        if description is not None:
            insert_at = _after_value(lines, description)
        else:
            title = next((i for i, l in enumerate(lines) if l.startswith("title:")), None)
            insert_at = _after_value(lines, title) if title is not None else len(lines)
        lines.insert(insert_at, f"group: {heading}")
        path.write_text("---\n" + "\n".join(lines) + text[match.end(1):], encoding="utf-8")
        stamped.append((target, heading))
    return stamped


def is_lore(lore):
    return (Path(lore) / "wiki").is_dir() and (Path(lore) / "CLAUDE.md").is_file()


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Regenerate a lore's index.md (and index/<Group>.md when split) from wiki/ frontmatter.")
    parser.add_argument("lore", help="the lore folder (needs wiki/ and CLAUDE.md)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--split", action="store_true", help="write a hub index.md plus index/<Group>.md files")
    mode.add_argument("--flat", action="store_true", help="remove index/ and write one flat index.md")
    parser.add_argument("--groups", action="store_true", help="list groups with page counts; write nothing")
    parser.add_argument("--seed-groups", action="store_true",
                        help="stamp group: from the current index headings, then regenerate")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the index on disk differs from what would be written; write nothing")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    lore = Path(args.lore).expanduser().resolve()
    if not is_lore(lore):
        print(f"ERROR: {lore} is not a lore (needs wiki/ and CLAUDE.md)", file=sys.stderr)
        return 2
    if args.groups:
        for name, count in list_groups(load_entries(lore)[0]):
            print(f"{name}\t{count}")
        return 0
    if args.check:
        drift = check(lore)
        for rel in drift:
            print(f"DRIFT {rel}")
        return 1 if drift else 0
    if args.seed_groups:
        for target, heading in seed_groups(lore):
            print(f"seeded: {target} (group: {heading})")
    elif is_curated(lore, load_entries(lore)[0]):
        print("ERROR: index.md is hand-curated and no page carries group:; run --seed-groups once",
              file=sys.stderr)
        return 1
    if args.flat and (lore / "index").is_dir():
        shutil.rmtree(lore / "index")
    split = True if args.split else False if args.flat else (lore / "index").is_dir()
    files, messages = render(lore, split)
    write_files(lore, files, split)
    for message in messages:
        print(message)
    return 0


if __name__ == "__main__":
    sys.exit(main())
