#!/usr/bin/env python3
"""Regenerate a lore's index from wiki/ frontmatter.

The only writer of <lore>/index.md and <lore>/index/<Group>.md. Part of the
lore plugin contract (skills/lore/SKILL.md, "Index regeneration"). Stdlib only.

Usage: lore_index.py <lore> [--split | --flat] [--groups] [--seed-groups] [--check]

Exit codes: 0 done (WARN:/NOTE: lines may be on stdout), 1 refusal or drift,
2 usage error or <lore> is not a lore (needs wiki/ and CLAUDE.md).
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

MARKER = ("<!-- generated by lore_index.py from wiki/ frontmatter — do not edit; "
          "set group:/description: in the page and re-run -->")
UNGROUPED = "Ungrouped"
DEPRECATED = "Deprecated"
ENTRY_CAP = 200          # every entry and hub line must be shorter than this
SPLIT_THRESHOLD = 200    # more entries than this -> NOTE suggesting --split
SCALAR_FIELDS = ("title", "description", "group", "status")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---(?:\n|\Z)", re.DOTALL)
INDEX_ENTRY_RE = re.compile(r"^- \[(?P<title>[^\]]+)\]\((?P<target>[^)]+)\)")
INDEX_HEADING_RE = re.compile(r"^##\s+(?P<heading>.+?)\s*$")


def scalar(value):
    """One frontmatter scalar: quotes stripped, trailing ` #comment` dropped."""
    value = value.strip()
    if value[:1] in ("'", '"'):
        end = value.find(value[0], 1)
        return value[1:end] if end != -1 else value[1:]
    cut = value.find(" #")
    return value[:cut].rstrip() if cut != -1 else value


def read_scalars(text):
    """The top-level SCALAR_FIELDS of a page's frontmatter, or None without one.

    Indented (nested) lines are ignored; a key whose value is a nested block
    reads as absent.
    """
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    fields = {}
    for line in match.group(1).split("\n"):
        if not line or line[0].isspace() or line.startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if sep and key.strip() in SCALAR_FIELDS and scalar(value):
            fields[key.strip()] = scalar(value)
    return fields


def load_entries(lore):
    """One entry per wiki/*.md (sorted by filename) plus the WARN lines raised.

    A page is never dropped: without frontmatter or a title it is listed from
    its filename, with an empty hook and no group.
    """
    entries, warnings = [], []
    for path in sorted((Path(lore) / "wiki").glob("*.md")):
        try:
            fields = read_scalars(path.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            fields = None
        if fields is None or not fields.get("title"):
            warnings.append(f"WARN: no frontmatter wiki/{path.name}")
            fields = fields or {}
        entries.append({
            "file": f"wiki/{path.name}",
            "title": fields.get("title") or path.stem.replace("_", " "),
            "hook": fields.get("description", ""),
            "group": fields.get("group"),
            "deprecated": fields.get("status") == "deprecated",
        })
    return entries, warnings


def heading_for(entry):
    if entry["deprecated"]:
        return DEPRECATED
    return entry["group"] or UNGROUPED


def group_entries(entries):
    """Ordered (heading, entries) pairs: headings case-insensitively, then
    Ungrouped, then Deprecated; entries by title, case-insensitively."""
    buckets = {}
    for entry in entries:
        buckets.setdefault(heading_for(entry), []).append(entry)
    ordinary = sorted((h for h in buckets if h not in (UNGROUPED, DEPRECATED)), key=str.casefold)
    special = [h for h in (UNGROUPED, DEPRECATED) if h in buckets]
    return [(h, sorted(buckets[h], key=lambda e: e["title"].casefold())) for h in ordinary + special]


def list_groups(entries):
    """(group, count) by the pages' own group value — deprecated pages count
    too, so the agent sees every group that exists. Ordered the same way
    group_entries orders headings (case-insensitively, then Ungrouped, then
    Deprecated last) so a page whose frontmatter literally sets
    group: Deprecated sorts where it renders, not alphabetically among the
    ordinary groups."""
    counts = {}
    for entry in entries:
        name = entry["group"] or UNGROUPED
        counts[name] = counts.get(name, 0) + 1
    ordinary = sorted((g for g in counts if g not in (UNGROUPED, DEPRECATED)), key=str.casefold)
    special = [g for g in (UNGROUPED, DEPRECATED) if g in counts]
    return [(g, counts[g]) for g in ordinary + special]


def entry_line(entry):
    """The index line for an entry, and the WARN raised when it had to be cut."""
    prefix = f"- [{entry['title']}]({entry['file']})"
    line = f"{prefix} — {entry['hook']}" if entry["hook"] else prefix
    if len(line) < ENTRY_CAP:
        return line, None
    warning = f"WARN: over-cap {entry['file']} ({len(line)} chars)"
    budget = ENTRY_CAP - 1 - len(prefix) - len(" — ") - len("…")
    if budget >= 0:
        hook = entry["hook"][:budget]
        if " " in hook:
            hook = hook.rsplit(" ", 1)[0]
        cut = f"{prefix} — {hook}…" if hook else prefix
        return cut, warning
    # The title+link prefix alone is already too long to fit any hook. Cut
    # the title instead, at a word boundary, same "…" convention as above.
    # Never cut the link target: a truncated path is a dead link, which is
    # worse than a long line — so if even an empty title can't fit under
    # the cap because the file path itself is too long, emit the line as-is.
    overhead = len(f"- [{''}…]({entry['file']})")
    title_budget = ENTRY_CAP - 1 - overhead
    if title_budget <= 0:
        return line, warning
    title = entry["title"][:title_budget]
    if " " in title:
        title = title.rsplit(" ", 1)[0]
    if not title:
        return line, warning
    return f"- [{title}…]({entry['file']})", warning


def render_flat(entries):
    lines, warnings = ["# Lore Index", MARKER], []
    for heading, members in group_entries(entries):
        lines += ["", f"## {heading}"]
        for entry in members:
            line, warning = entry_line(entry)
            lines.append(line)
            if warning:
                warnings.append(warning)
    return "\n".join(lines) + "\n", warnings


def group_filename(heading):
    return heading.replace(" ", "_").replace("/", "_") + ".md"


def hub_line(heading, members):
    """`- [Group](index/Group.md) — <n> pages: <titles>` cut under the cap at a
    title boundary; `, …` marks the cut.

    The link target is never truncated. If the heading/filename alone leave
    no room even for a bare "…" under the cap, the full, uncut line is
    emitted instead — cutting titles wouldn't bring it under the cap either,
    so there is nothing to gain from hiding them (same precedent as
    entry_line's pathological long-filename case).
    """
    n = len(members)
    base = f"- [{heading}](index/{group_filename(heading)}) — {n} page{'s' if n != 1 else ''}: "
    titles = [entry["title"] for entry in members]
    naive = base + ", ".join(titles)
    if len(base + "…") >= ENTRY_CAP:
        return naive
    chosen = []
    for title in titles:
        last = len(chosen) + 1 == len(titles)
        candidate = base + ", ".join(chosen + [title]) + ("" if last else ", …")
        if len(candidate) >= ENTRY_CAP:
            break
        chosen.append(title)
    if len(chosen) == len(titles):
        return naive
    return base + ", ".join(chosen) + (", …" if chosen else "…")


def render_split(entries):
    """A hub index.md plus one index/<Group>.md per heading."""
    files, warnings = {}, []
    hub = ["# Lore Index", MARKER, ""]
    for heading, members in group_entries(entries):
        hub.append(hub_line(heading, members))
        lines = [f"# {heading}", MARKER, ""]
        for entry in members:
            line, warning = entry_line(entry)
            lines.append(line)
            if warning:
                warnings.append(warning)
        files[f"index/{group_filename(heading)}"] = "\n".join(lines) + "\n"
    files["index.md"] = "\n".join(hub) + "\n"
    return files, warnings


def render(lore, split=None):
    """{relative path: text} for the index files, plus the WARN/NOTE lines.

    split=None reads the current mode from disk (index/ exists → split). The
    dashboard calls this to detect drift; the CLI writes what it returns.
    """
    lore = Path(lore)
    if split is None:
        split = (lore / "index").is_dir()
    entries, messages = load_entries(lore)
    if split:
        files, warnings = render_split(entries)
    else:
        text, warnings = render_flat(entries)
        files = {"index.md": text}
        if len(entries) > SPLIT_THRESHOLD:
            warnings.append(f"NOTE: {len(entries)} entries > {SPLIT_THRESHOLD}; run with --split to split the index")
    return files, messages + warnings


def write_files(lore, files):
    """Write every rendered file; in split mode remove index/*.md files that
    no longer correspond to a heading — the script owns that directory."""
    lore = Path(lore)
    for rel, text in files.items():
        (lore / rel).parent.mkdir(exist_ok=True)
        (lore / rel).write_text(text, encoding="utf-8")
    if any(rel.startswith("index/") for rel in files):
        for stale in (lore / "index").glob("*.md"):
            if f"index/{stale.name}" not in files:
                stale.unlink()


def check(lore):
    """Relative paths whose on-disk content differs from a fresh render —
    missing files and stale index/*.md files included. Sorted."""
    lore = Path(lore)
    files, _ = render(lore)
    drift = []
    for rel, text in files.items():
        try:
            current = (lore / rel).read_text(encoding="utf-8")
        except OSError:
            current = None
        if current != text:
            drift.append(rel)
    if (lore / "index").is_dir():
        for stale in (lore / "index").glob("*.md"):
            if f"index/{stale.name}" not in files:
                drift.append(f"index/{stale.name}")
    return sorted(drift)


def is_lore(lore):
    return (Path(lore) / "wiki").is_dir() and (Path(lore) / "CLAUDE.md").is_file()


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Regenerate a lore's index.md (and index/<Group>.md when split) from wiki/ frontmatter.")
    parser.add_argument("lore", help="the lore folder (needs wiki/ and CLAUDE.md)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--split", action="store_true", help="write a hub index.md plus index/<Group>.md files")
    mode.add_argument("--flat", action="store_true", help="remove index/ and write one flat index.md")
    parser.add_argument("--groups", action="store_true", help="list groups with page counts; write nothing")
    parser.add_argument("--seed-groups", action="store_true",
                        help="stamp group: from the current index headings, then regenerate")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the index on disk differs from what would be written; write nothing")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    lore = Path(args.lore).expanduser().resolve()
    if not is_lore(lore):
        print(f"ERROR: {lore} is not a lore (needs wiki/ and CLAUDE.md)", file=sys.stderr)
        return 2
    if args.groups:
        for name, count in list_groups(load_entries(lore)[0]):
            print(f"{name}\t{count}")
        return 0
    if args.check:
        drift = check(lore)
        for rel in drift:
            print(f"DRIFT {rel}")
        return 1 if drift else 0
    if args.flat and (lore / "index").is_dir():
        shutil.rmtree(lore / "index")
    split = True if args.split else False if args.flat else None
    files, messages = render(lore, split)
    write_files(lore, files)
    for message in messages:
        print(message)
    return 0


if __name__ == "__main__":
    sys.exit(main())
