"""Tests for scripts/lore_index.py — run with: python3 -m unittest discover scripts"""
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import lore_index
from lore_index import DEPRECATED, ENTRY_CAP, MARKER, UNGROUPED, load_entries, read_scalars

SCRIPT = Path(__file__).resolve().parent / "lore_index.py"


def page(title, group=None, description=None, status=None, frontmatter=True):
    """A minimal wiki page. description=None -> 'about <title>'."""
    if not frontmatter:
        return f"# {title}\n\nbody\n"
    lines = ["---", "type: concept", f"title: {title}",
             f"description: {description if description is not None else 'about ' + title}"]
    if group:
        lines.append(f"group: {group}")
    lines += ["tags: [x]", "generated:", "  by: lore/test", "  at: 2026-08-01"]
    if status:
        lines.append(f"status: {status}")
    return "\n".join(lines) + "\n---\n\nbody\n"


def make_lore(pages=None, index_text=None):
    """A lore with wiki/, raw/, CLAUDE.md and the given wiki pages (name -> text)."""
    root = Path(tempfile.mkdtemp())
    (root / "wiki").mkdir()
    (root / "raw").mkdir()
    (root / "CLAUDE.md").write_text("# schema\n")
    for name, text in (pages or {}).items():
        (root / "wiki" / name).write_text(text)
    if index_text is not None:
        (root / "index.md").write_text(index_text)
    return root


def run(lore, *flags):
    return subprocess.run([sys.executable, str(SCRIPT), str(lore), *flags],
                          capture_output=True, text=True)


class TestReadScalars(unittest.TestCase):
    def test_no_frontmatter_is_none(self):
        self.assertIsNone(read_scalars("# Just a heading\n\ntext\n"))

    def test_top_level_scalars_only(self):
        fields = read_scalars("---\ntype: concept\ntitle: A Page\ndescription: about it\n"
                              "group: Hardware\nstatus: draft\ntags: [x]\n"
                              "generated:\n  by: lore/test\n  at: 2026-08-01\n---\nbody\n")
        self.assertEqual(fields, {"title": "A Page", "description": "about it",
                                  "group": "Hardware", "status": "draft"})

    def test_quotes_stripped_and_trailing_comment_dropped(self):
        fields = read_scalars('---\ntitle: "Quoted: Title"\ngroup: Hardware   # the heading\n---\n')
        self.assertEqual(fields, {"title": "Quoted: Title", "group": "Hardware"})

    def test_key_followed_by_nested_block_reads_as_absent(self):
        fields = read_scalars("---\ntitle: A\ndescription:\n  - not a scalar\n---\n")
        self.assertEqual(fields, {"title": "A"})

    def test_frontmatter_without_trailing_newline_is_read(self):
        self.assertEqual(read_scalars("---\ntitle: A\n---"), {"title": "A"})


class TestLoadEntries(unittest.TestCase):
    def test_one_entry_per_page_sorted_by_filename(self):
        lore = make_lore({"B.md": page("B", "G2"), "A.md": page("A", "G1", status="deprecated")})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, [])
        self.assertEqual(entries, [
            {"file": "wiki/A.md", "title": "A", "hook": "about A", "group": "G1", "deprecated": True},
            {"file": "wiki/B.md", "title": "B", "hook": "about B", "group": "G2", "deprecated": False},
        ])

    def test_page_without_frontmatter_is_kept_with_a_warning(self):
        lore = make_lore({"Old_Note.md": page("Old Note", frontmatter=False)})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/Old_Note.md"])
        self.assertEqual(entries[0], {"file": "wiki/Old_Note.md", "title": "Old Note", "hook": "",
                                      "group": None, "deprecated": False})

    def test_page_with_frontmatter_but_no_title_warns_and_uses_filename(self):
        lore = make_lore({"No_Title.md": "---\ntype: concept\ndescription: d\n---\n"})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/No_Title.md"])
        self.assertEqual((entries[0]["title"], entries[0]["hook"]), ("No Title", "d"))

    def test_constants(self):
        self.assertEqual((UNGROUPED, DEPRECATED, ENTRY_CAP), ("Ungrouped", "Deprecated", 200))
        self.assertTrue(MARKER.startswith("<!-- generated by lore_index.py"))


from lore_index import entry_line, group_entries, render, render_flat, write_files  # noqa: E402


class TestGrouping(unittest.TestCase):
    def test_headings_sorted_case_insensitively_with_ungrouped_and_deprecated_last(self):
        lore = make_lore({
            "A.md": page("A", "zeta"), "B.md": page("B", "Alpha"), "C.md": page("C"),
            "D.md": page("D", "Alpha", status="deprecated"), "E.md": page("E", "Beta"),
        })
        entries, _ = load_entries(lore)
        headings = [h for h, _ in group_entries(entries)]
        self.assertEqual(headings, ["Alpha", "Beta", "zeta", "Ungrouped", "Deprecated"])

    def test_entries_sorted_by_title_case_insensitively(self):
        lore = make_lore({"1.md": page("beta", "G"), "2.md": page("Alpha", "G"), "3.md": page("Gamma", "G")})
        entries, _ = load_entries(lore)
        self.assertEqual([e["title"] for e in group_entries(entries)[0][1]], ["Alpha", "beta", "Gamma"])

    def test_deprecated_wins_over_group(self):
        lore = make_lore({"A.md": page("A", "Hardware", status="deprecated")})
        entries, _ = load_entries(lore)
        self.assertEqual(group_entries(entries), [("Deprecated", entries)])


class TestEntryLine(unittest.TestCase):
    def test_line_is_title_link_and_description(self):
        line, warning = entry_line({"file": "wiki/A_Page.md", "title": "A Page", "hook": "the hook",
                                    "group": "G", "deprecated": False})
        self.assertEqual(line, "- [A Page](wiki/A_Page.md) — the hook")
        self.assertIsNone(warning)

    def test_empty_hook_has_no_dash(self):
        line, _ = entry_line({"file": "wiki/A.md", "title": "A", "hook": "", "group": None, "deprecated": False})
        self.assertEqual(line, "- [A](wiki/A.md)")

    def test_over_cap_hook_is_cut_at_a_word_boundary_with_ellipsis_and_warning(self):
        entry = {"file": "wiki/A.md", "title": "A", "hook": "word " * 60, "group": "G", "deprecated": False}
        line, warning = entry_line(entry)
        self.assertLess(len(line), ENTRY_CAP)
        self.assertTrue(line.endswith("…"))
        self.assertEqual(line[:-1].split(" ")[-1], "word")          # no partial word before the ellipsis
        self.assertEqual(warning, f"WARN: over-cap wiki/A.md ({len('- [A](wiki/A.md) — ' + 'word ' * 60)} chars)")

    def test_line_of_exactly_199_chars_is_not_cut(self):
        hook = "x" * (199 - len("- [A](wiki/A.md) — "))
        line, warning = entry_line({"file": "wiki/A.md", "title": "A", "hook": hook, "group": "G", "deprecated": False})
        self.assertEqual((len(line), warning), (199, None))

    def test_prefix_alone_over_cap_cuts_the_title_not_the_link(self):
        entry = {"file": "wiki/A.md", "title": "T" * 190, "hook": "x", "group": "G", "deprecated": False}
        naive = f"- [{entry['title']}](wiki/A.md) — x"
        line, warning = entry_line(entry)
        self.assertLess(len(line), ENTRY_CAP)
        self.assertTrue(line.endswith("…](wiki/A.md)"))              # link target intact
        self.assertEqual(warning, f"WARN: over-cap wiki/A.md ({len(naive)} chars)")

    def test_pathological_long_filename_is_emitted_as_is_with_warning(self):
        long_file = "wiki/" + "f" * 250 + ".md"
        entry = {"file": long_file, "title": "T", "hook": "x", "group": "G", "deprecated": False}
        naive = f"- [T]({long_file}) — x"
        line, warning = entry_line(entry)
        self.assertEqual(line, naive)                                 # not truncated: cap can't be met
        self.assertEqual(warning, f"WARN: over-cap {long_file} ({len(naive)} chars)")


class TestRenderFlat(unittest.TestCase):
    def test_layout(self):
        lore = make_lore({"B.md": page("B", "Hardware"), "A.md": page("A", "Hardware"),
                          "N.md": page("N", frontmatter=False), "D.md": page("D", "Hardware", status="deprecated")})
        files, messages = render(lore)
        self.assertEqual(list(files), ["index.md"])
        self.assertEqual(files["index.md"], "\n".join([
            "# Lore Index", MARKER, "",
            "## Hardware",
            "- [A](wiki/A.md) — about A",
            "- [B](wiki/B.md) — about B",
            "",
            "## Ungrouped",
            "- [N](wiki/N.md)",
            "",
            "## Deprecated",
            "- [D](wiki/D.md) — about D",
        ]) + "\n")
        self.assertEqual(messages, ["WARN: no frontmatter wiki/N.md"])

    def test_empty_wiki_renders_header_only(self):
        files, messages = render(make_lore())
        self.assertEqual((files["index.md"], messages), (f"# Lore Index\n{MARKER}\n", []))

    def test_over_cap_warning_is_reported(self):
        lore = make_lore({"A.md": page("A", "G", description="word " * 60)})
        _, messages = render(lore)
        self.assertEqual(len(messages), 1)
        self.assertTrue(messages[0].startswith("WARN: over-cap wiki/A.md ("))


class TestCli(unittest.TestCase):
    def test_writes_index_md_and_exits_0(self):
        lore = make_lore({"A.md": page("A", "G")})
        proc = run(lore)
        self.assertEqual((proc.returncode, proc.stdout, proc.stderr), (0, "", ""))
        self.assertEqual((lore / "index.md").read_text(), f"# Lore Index\n{MARKER}\n\n## G\n- [A](wiki/A.md) — about A\n")

    def test_warnings_go_to_stdout(self):
        lore = make_lore({"N.md": page("N", frontmatter=False)})
        proc = run(lore)
        self.assertEqual((proc.returncode, proc.stdout), (0, "WARN: no frontmatter wiki/N.md\n"))

    def test_second_run_is_byte_identical(self):
        lore = make_lore({"A.md": page("A", "G"), "B.md": page("B", "H")})
        run(lore)
        first = (lore / "index.md").read_bytes()
        run(lore)
        self.assertEqual((lore / "index.md").read_bytes(), first)

    def test_not_a_lore_exits_2_and_writes_nothing(self):
        root = Path(tempfile.mkdtemp())
        proc = run(root)
        self.assertEqual(proc.returncode, 2)
        self.assertIn("ERROR:", proc.stderr)
        self.assertFalse((root / "index.md").exists())

    def test_lore_needs_claude_md_not_index_md(self):
        lore = make_lore({"A.md": page("A", "G")})
        (lore / "CLAUDE.md").unlink()
        self.assertEqual(run(lore).returncode, 2)


from lore_index import check, list_groups  # noqa: E402


class TestGroupsFlag(unittest.TestCase):
    def test_lists_group_values_with_counts_including_deprecated_pages(self):
        lore = make_lore({"A.md": page("A", "zeta"), "B.md": page("B", "Alpha"),
                          "C.md": page("C", "Alpha", status="deprecated"), "N.md": page("N")})
        entries, _ = load_entries(lore)
        self.assertEqual(list_groups(entries), [("Alpha", 2), ("zeta", 1), ("Ungrouped", 1)])
        proc = run(lore, "--groups")
        self.assertEqual((proc.returncode, proc.stdout), (0, "Alpha\t2\nzeta\t1\nUngrouped\t1\n"))
        self.assertFalse((lore / "index.md").exists())          # --groups never writes

    def test_a_page_with_literal_group_deprecated_sorts_like_its_heading(self):
        # group_entries buckets a page whose frontmatter literally sets
        # group: Deprecated under "## Deprecated" (heading_for returns the
        # group verbatim for a non-deprecated page); --groups must order it
        # the same way, not alphabetically among ordinary groups.
        lore = make_lore({"A.md": page("A", "Deprecated"), "B.md": page("B", "Alpha")})
        entries, _ = load_entries(lore)
        self.assertEqual(list_groups(entries), [("Alpha", 1), ("Deprecated", 1)])
        self.assertEqual([h for h, _ in group_entries(entries)], ["Alpha", "Deprecated"])


class TestCheckFlag(unittest.TestCase):
    def test_fresh_index_is_not_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        run(lore)
        self.assertEqual(check(lore), [])
        proc = run(lore, "--check")
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))

    def test_new_page_without_regeneration_is_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        run(lore)
        (lore / "wiki" / "B.md").write_text(page("B", "G"))
        self.assertEqual(check(lore), ["index.md"])
        proc = run(lore, "--check")
        self.assertEqual((proc.returncode, proc.stdout), (1, "DRIFT index.md\n"))
        self.assertNotIn("B", (lore / "index.md").read_text())   # --check never writes

    def test_missing_index_is_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        self.assertEqual(check(lore), ["index.md"])


from lore_index import SPLIT_THRESHOLD, group_filename, hub_line, render_split  # noqa: E402


def many_pages(n, group="G"):
    return {f"P{i:03d}.md": page(f"Page {i:03d}", group) for i in range(n)}


class TestSplitRender(unittest.TestCase):
    def test_group_filename_replaces_spaces_and_slashes(self):
        self.assertEqual(group_filename("Power / Thermal Mgmt"), "Power___Thermal_Mgmt.md")

    def test_hub_line_lists_count_and_titles(self):
        members = [{"file": "wiki/A.md", "title": "A", "hook": "", "group": "Hardware", "deprecated": False},
                   {"file": "wiki/B.md", "title": "B", "hook": "", "group": "Hardware", "deprecated": False}]
        self.assertEqual(hub_line("Hardware", members), "- [Hardware](index/Hardware.md) — 2 pages: A, B")
        self.assertEqual(hub_line("Hardware", members[:1]), "- [Hardware](index/Hardware.md) — 1 page: A")

    def test_hub_line_is_cut_at_a_title_boundary_under_the_cap(self):
        members = [{"file": f"wiki/{i}.md", "title": f"A fairly long page title number {i}", "hook": "",
                    "group": "G", "deprecated": False} for i in range(40)]
        line = hub_line("G", members)
        self.assertLess(len(line), ENTRY_CAP)
        self.assertTrue(line.endswith(", …"))
        self.assertTrue(line.startswith("- [G](index/G.md) — 40 pages: A fairly long page title number 0, "))

    def test_hub_line_with_no_room_for_any_title_still_fits_under_cap(self):
        # The link/heading is short but the one title is too long to fit
        # alongside it — the line still must come in under the cap, by
        # dropping the whole title in favour of a bare ellipsis rather than
        # truncating the link target.
        members = [{"file": "wiki/A.md", "title": "T" * 190, "hook": "", "group": "G", "deprecated": False}]
        line = hub_line("G", members)
        self.assertEqual(line, "- [G](index/G.md) — 1 page: …")
        self.assertLess(len(line), ENTRY_CAP)

    def test_hub_line_with_pathological_long_heading_is_emitted_as_is(self):
        # The heading/filename alone (the link target) leave no room even
        # for a bare "…" under the cap. Never truncate the link target:
        # emit the full, uncut line instead (same precedent as entry_line's
        # pathological-long-filename case).
        heading = "H" * 250
        members = [{"file": "wiki/A.md", "title": "A", "hook": "", "group": heading, "deprecated": False}]
        naive = f"- [{heading}](index/{group_filename(heading)}) — 1 page: A"
        line = hub_line(heading, members)
        self.assertEqual(line, naive)
        self.assertGreaterEqual(len(line), ENTRY_CAP)   # cannot fit without truncating the link target

    def test_split_files(self):
        lore = make_lore({"A.md": page("A", "Hardware"), "B.md": page("B", "Software"),
                          "D.md": page("D", "Hardware", status="deprecated")})
        entries, _ = load_entries(lore)
        files, warnings = render_split(entries)
        self.assertEqual(sorted(files), ["index.md", "index/Deprecated.md", "index/Hardware.md", "index/Software.md"])
        self.assertEqual(files["index.md"], "\n".join([
            "# Lore Index", MARKER, "",
            "- [Hardware](index/Hardware.md) — 1 page: A",
            "- [Software](index/Software.md) — 1 page: B",
            "- [Deprecated](index/Deprecated.md) — 1 page: D",
        ]) + "\n")
        self.assertEqual(files["index/Hardware.md"],
                         f"# Hardware\n{MARKER}\n\n- [A](wiki/A.md) — about A\n")   # paths stay lore-relative
        self.assertEqual(warnings, [])

    def test_hub_line_accepts_a_filename_override(self):
        members = [{"file": "wiki/A.md", "title": "A", "hook": "", "group": "G", "deprecated": False}]
        self.assertEqual(hub_line("G", members, "G_2.md"), "- [G](index/G_2.md) — 1 page: A")

    def test_render_split_disambiguates_a_filename_collision(self):
        # "Power/Thermal" and "Power Thermal" both group_filename() to
        # Power_Thermal.md. Neither group's pages may be silently dropped:
        # the second heading claimed (group_entries orders "Power Thermal"
        # before "Power/Thermal" casefold) gets a _2 suffix, a WARN, and its
        # own hub line pointing at the file it actually got.
        lore = make_lore({"A.md": page("A", "Power/Thermal"), "B.md": page("B", "Power Thermal")})
        entries, _ = load_entries(lore)
        files, warnings = render_split(entries)
        self.assertEqual(sorted(files), ["index.md", "index/Power_Thermal.md", "index/Power_Thermal_2.md"])
        self.assertEqual(files["index/Power_Thermal.md"], f"# Power Thermal\n{MARKER}\n\n- [B](wiki/B.md) — about B\n")
        self.assertEqual(files["index/Power_Thermal_2.md"], f"# Power/Thermal\n{MARKER}\n\n- [A](wiki/A.md) — about A\n")
        hub = files["index.md"]
        self.assertIn("- [Power Thermal](index/Power_Thermal.md) — 1 page: B", hub)
        self.assertIn("- [Power/Thermal](index/Power_Thermal_2.md) — 1 page: A", hub)
        self.assertEqual(warnings, ['WARN: group filename collision; "Power/Thermal" written as index/Power_Thermal_2.md'])

    def test_render_split_disambiguates_a_three_way_filename_collision(self):
        lore = make_lore({"A.md": page("A", "Power Thermal"), "B.md": page("B", "Power/Thermal"),
                          "C.md": page("C", "Power_Thermal")})
        entries, _ = load_entries(lore)
        files, warnings = render_split(entries)
        self.assertEqual(sorted(files),
                         ["index.md", "index/Power_Thermal.md", "index/Power_Thermal_2.md", "index/Power_Thermal_3.md"])
        self.assertEqual(warnings, [
            'WARN: group filename collision; "Power/Thermal" written as index/Power_Thermal_2.md',
            'WARN: group filename collision; "Power_Thermal" written as index/Power_Thermal_3.md',
        ])


class TestSplitCli(unittest.TestCase):
    def test_note_above_threshold_flat_still_written(self):
        lore = make_lore(many_pages(SPLIT_THRESHOLD + 1))
        proc = run(lore)
        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, f"NOTE: {SPLIT_THRESHOLD + 1} entries > 200; run with --split to split the index\n")
        self.assertFalse((lore / "index").exists())
        self.assertIn("## G", (lore / "index.md").read_text())

    def test_no_note_at_exactly_the_threshold(self):
        proc = run(make_lore(many_pages(SPLIT_THRESHOLD)))
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))

    def test_split_flag_writes_hub_and_group_files(self):
        lore = make_lore({"A.md": page("A", "Hardware"), "B.md": page("B", "Software")})
        proc = run(lore, "--split")
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))
        self.assertEqual(sorted(p.name for p in (lore / "index").glob("*.md")), ["Hardware.md", "Software.md"])
        self.assertIn("- [Hardware](index/Hardware.md) — 1 page: A", (lore / "index.md").read_text())

    def test_split_is_sticky_and_removes_stale_group_files(self):
        lore = make_lore({"A.md": page("A", "Hardware"), "B.md": page("B", "Software")})
        run(lore, "--split")
        (lore / "wiki" / "B.md").unlink()
        (lore / "wiki" / "C.md").write_text(page("C", "Thermal"))
        proc = run(lore)                                        # no flag: stays split
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))
        self.assertEqual(sorted(p.name for p in (lore / "index").glob("*.md")), ["Hardware.md", "Thermal.md"])
        self.assertEqual(check(lore), [])

    def test_split_is_sticky_and_index_dir_survives_an_emptied_wiki(self):
        # write_files must key its stale-index/*.md cleanup off split mode
        # explicitly, not off whether the rendered files happen to include
        # an "index/" entry — a wholly emptied wiki/ renders zero headings,
        # so files is just {"index.md": ...}, yet index/ must still be
        # cleared out (not left with a stale group file) and kept (not
        # deleted — only --flat removes the directory itself).
        lore = make_lore({"A.md": page("A", "Alpha")})
        run(lore, "--split")
        (lore / "wiki" / "A.md").unlink()
        proc = run(lore)                                        # no flag: stays split
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))
        self.assertTrue((lore / "index").is_dir())
        self.assertEqual(list((lore / "index").glob("*.md")), [])
        self.assertEqual((lore / "index.md").read_text(), f"# Lore Index\n{MARKER}\n\n")
        self.assertEqual(check(lore), [])

    def test_flat_flag_removes_index_dir(self):
        lore = make_lore({"A.md": page("A", "Hardware")})
        run(lore, "--split")
        proc = run(lore, "--flat")
        self.assertEqual(proc.returncode, 0)
        self.assertFalse((lore / "index").exists())
        self.assertIn("## Hardware\n- [A](wiki/A.md) — about A", (lore / "index.md").read_text())

    def test_split_and_flat_together_is_a_usage_error(self):
        self.assertEqual(run(make_lore(), "--split", "--flat").returncode, 2)

    def test_check_sees_a_stale_group_file(self):
        lore = make_lore({"A.md": page("A", "Hardware")})
        run(lore, "--split")
        (lore / "index" / "Old.md").write_text("# Old\n")
        self.assertEqual(check(lore), ["index/Old.md"])


from lore_index import is_curated, read_current_index, seed_groups  # noqa: E402

CURATED = ("# Lore Index\n\n## RF\n- [A](wiki/A.md) — old hook\n- [B](wiki/B.md) — old hook\n\n"
           "## Deprecated\n- [D](wiki/D.md) — gone\n")


class TestUpgradeGuard(unittest.TestCase):
    def _old_lore(self):
        return make_lore({"A.md": page("A"), "B.md": page("B"), "D.md": page("D", status="deprecated")},
                         index_text=CURATED)

    def test_read_current_index_pairs_and_marker(self):
        pairs, generated = read_current_index(self._old_lore())
        self.assertEqual(pairs, [("RF", "wiki/A.md"), ("RF", "wiki/B.md"), ("Deprecated", "wiki/D.md")])
        self.assertFalse(generated)

    def test_read_current_index_follows_hub_lines(self):
        lore = make_lore({"A.md": page("A", "Hardware")})
        run(lore, "--split")
        pairs, generated = read_current_index(lore)
        self.assertEqual((pairs, generated), ([("Hardware", "wiki/A.md")], True))

    def test_curated_index_without_groups_is_refused(self):
        lore = self._old_lore()
        self.assertTrue(is_curated(lore, load_entries(lore)[0]))
        proc = run(lore)
        self.assertEqual(proc.returncode, 1)
        self.assertEqual(proc.stderr, "ERROR: index.md is hand-curated and no page carries group:; run --seed-groups once\n")
        self.assertEqual((lore / "index.md").read_text(), CURATED)      # untouched

    def test_generated_index_is_never_curated(self):
        lore = make_lore({"N.md": page("N", frontmatter=False)})        # renders under Ungrouped
        self.assertEqual(run(lore).returncode, 0)
        self.assertEqual(run(lore).returncode, 0)                        # second run: marker present
        self.assertFalse(is_curated(lore, load_entries(lore)[0]))

    def test_index_with_only_ungrouped_or_deprecated_headings_is_not_curated(self):
        lore = make_lore({"A.md": page("A")}, index_text="# Lore Index\n\n## Ungrouped\n- [A](wiki/A.md)\n")
        self.assertFalse(is_curated(lore, load_entries(lore)[0]))

    def test_missing_index_is_not_curated(self):
        lore = make_lore({"A.md": page("A")})
        self.assertFalse(is_curated(lore, load_entries(lore)[0]))

    def test_any_page_with_a_group_disables_the_guard(self):
        lore = self._old_lore()
        (lore / "wiki" / "A.md").write_text(page("A", "RF"))
        self.assertEqual(run(lore).returncode, 0)

    def test_check_ignores_the_guard(self):
        self.assertEqual(run(self._old_lore(), "--check").returncode, 1)     # drift, not the ERROR

    def test_heading_with_trailing_whitespace_is_read_clean(self):
        lore = make_lore({"A.md": page("A")}, index_text="# Lore Index\n\n## RF   \n- [A](wiki/A.md)\n")
        pairs, _ = read_current_index(lore)
        self.assertEqual(pairs, [("RF", "wiki/A.md")])
        self.assertTrue(is_curated(lore, load_entries(lore)[0]))

    def test_missing_split_group_file_yields_no_pairs_for_that_heading(self):
        lore = make_lore({"A.md": page("A", "Hardware"), "B.md": page("B", "Software")})
        run(lore, "--split")
        (lore / "index" / "Hardware.md").unlink()
        pairs, generated = read_current_index(lore)
        self.assertEqual(pairs, [("Software", "wiki/B.md")])
        self.assertTrue(generated)


class TestSeedGroups(unittest.TestCase):
    def test_stamps_group_after_description_and_regenerates(self):
        lore = make_lore({"A.md": page("A"), "B.md": page("B"), "D.md": page("D", status="deprecated")},
                         index_text=CURATED)
        proc = run(lore, "--seed-groups")
        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "seeded: wiki/A.md (group: RF)\nseeded: wiki/B.md (group: RF)\n")
        self.assertIn("description: about A\ngroup: RF\ntags:", (lore / "wiki" / "A.md").read_text())
        self.assertNotIn("group:", (lore / "wiki" / "D.md").read_text())     # Deprecated entries skipped
        index = (lore / "index.md").read_text()
        self.assertIn(MARKER, index)
        self.assertIn("## RF\n- [A](wiki/A.md) — about A\n- [B](wiki/B.md) — about B\n", index)
        self.assertIn("## Deprecated\n- [D](wiki/D.md) — about D\n", index)

    def test_seed_is_idempotent(self):
        lore = make_lore({"A.md": page("A")}, index_text=CURATED)
        run(lore, "--seed-groups")
        proc = run(lore, "--seed-groups")
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))
        self.assertEqual((lore / "wiki" / "A.md").read_text().count("group:"), 1)

    def test_seed_falls_back_to_title_line_and_skips_pages_without_frontmatter(self):
        lore = make_lore({"A.md": "---\ntype: concept\ntitle: A\ntags: [x]\n---\nbody\n",
                          "N.md": page("N", frontmatter=False)},
                         index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n- [N](wiki/N.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        self.assertEqual((lore / "wiki" / "A.md").read_text(), "---\ntype: concept\ntitle: A\ngroup: RF\ntags: [x]\n---\nbody\n")

    def test_seed_appends_group_when_frontmatter_has_no_description_or_title(self):
        lore = make_lore({"A.md": "---\ntype: concept\ntags: [x]\n---\nbody\n"},
                         index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        self.assertEqual((lore / "wiki" / "A.md").read_text(),
                         "---\ntype: concept\ntags: [x]\ngroup: RF\n---\nbody\n")

    def test_seed_skips_a_page_with_no_frontmatter_even_under_a_real_heading(self):
        lore = make_lore({"A.md": page("A", frontmatter=False)},
                         index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [])
        self.assertEqual((lore / "wiki" / "A.md").read_text(), page("A", frontmatter=False))

    def test_seed_skips_an_index_entry_whose_file_does_not_exist(self):
        lore = make_lore({}, index_text="# Lore Index\n\n## RF\n- [Ghost](wiki/Ghost.md)\n")
        self.assertEqual(seed_groups(lore), [])

    def test_seed_preserves_a_block_scalar_description(self):
        text = "---\ntype: concept\ntitle: A\ndescription: |\n  line one\n  line two\ntags: [x]\n---\nbody\n"
        lore = make_lore({"A.md": text}, index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        result = (lore / "wiki" / "A.md").read_text()
        self.assertEqual(result, "---\ntype: concept\ntitle: A\ndescription: |\n  line one\n  line two\n"
                                  "group: RF\ntags: [x]\n---\nbody\n")
        self.assertEqual(read_scalars(result)["description"], "|")   # pre-existing read_scalars limitation, unaffected

    def test_seed_preserves_a_block_scalar_with_an_internal_blank_line(self):
        text = "---\ntype: concept\ntitle: A\ndescription: |\n  line one\n\n  line two\ntags: [x]\n---\nbody\n"
        lore = make_lore({"A.md": text}, index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        self.assertEqual((lore / "wiki" / "A.md").read_text(),
                         "---\ntype: concept\ntitle: A\ndescription: |\n  line one\n\n  line two\n"
                         "group: RF\ntags: [x]\n---\nbody\n")

    def test_seed_preserves_a_folded_scalar_description(self):
        text = "---\ntype: concept\ntitle: A\ndescription: >\n  line one\n  line two\ntags: [x]\n---\nbody\n"
        lore = make_lore({"A.md": text}, index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        self.assertEqual((lore / "wiki" / "A.md").read_text(),
                         "---\ntype: concept\ntitle: A\ndescription: >\n  line one\n  line two\n"
                         "group: RF\ntags: [x]\n---\nbody\n")

    def test_seed_preserves_a_multiline_title_fallback(self):
        text = "---\ntype: concept\ntitle: |\n  A Title\n  Continued\ntags: [x]\n---\nbody\n"
        lore = make_lore({"A.md": text}, index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        self.assertEqual(seed_groups(lore), [("wiki/A.md", "RF")])
        self.assertEqual((lore / "wiki" / "A.md").read_text(),
                         "---\ntype: concept\ntitle: |\n  A Title\n  Continued\ngroup: RF\ntags: [x]\n---\nbody\n")

    def test_seed_is_idempotent_on_a_page_with_a_block_scalar_description(self):
        text = "---\ntype: concept\ntitle: A\ndescription: |\n  line one\n  line two\ntags: [x]\n---\nbody\n"
        lore = make_lore({"A.md": text}, index_text="# Lore Index\n\n## RF\n- [A](wiki/A.md)\n")
        seed_groups(lore)
        first = (lore / "wiki" / "A.md").read_text()
        self.assertEqual(seed_groups(lore), [])
        self.assertEqual((lore / "wiki" / "A.md").read_text(), first)


if __name__ == "__main__":
    unittest.main()
