"""Tests for scripts/lore_index.py — run with: python3 -m unittest discover scripts"""
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import lore_index
from lore_index import DEPRECATED, ENTRY_CAP, MARKER, UNGROUPED, load_entries, read_scalars

SCRIPT = Path(__file__).resolve().parent / "lore_index.py"


def page(title, group=None, description=None, status=None, frontmatter=True):
    """A minimal wiki page. description=None -> 'about <title>'."""
    if not frontmatter:
        return f"# {title}\n\nbody\n"
    lines = ["---", "type: concept", f"title: {title}",
             f"description: {description if description is not None else 'about ' + title}"]
    if group:
        lines.append(f"group: {group}")
    lines += ["tags: [x]", "generated:", "  by: lore/test", "  at: 2026-08-01"]
    if status:
        lines.append(f"status: {status}")
    return "\n".join(lines) + "\n---\n\nbody\n"


def make_lore(pages=None, index_text=None):
    """A lore with wiki/, raw/, CLAUDE.md and the given wiki pages (name -> text)."""
    root = Path(tempfile.mkdtemp())
    (root / "wiki").mkdir()
    (root / "raw").mkdir()
    (root / "CLAUDE.md").write_text("# schema\n")
    for name, text in (pages or {}).items():
        (root / "wiki" / name).write_text(text)
    if index_text is not None:
        (root / "index.md").write_text(index_text)
    return root


def run(lore, *flags):
    return subprocess.run([sys.executable, str(SCRIPT), str(lore), *flags],
                          capture_output=True, text=True)


class TestReadScalars(unittest.TestCase):
    def test_no_frontmatter_is_none(self):
        self.assertIsNone(read_scalars("# Just a heading\n\ntext\n"))

    def test_top_level_scalars_only(self):
        fields = read_scalars("---\ntype: concept\ntitle: A Page\ndescription: about it\n"
                              "group: Hardware\nstatus: draft\ntags: [x]\n"
                              "generated:\n  by: lore/test\n  at: 2026-08-01\n---\nbody\n")
        self.assertEqual(fields, {"title": "A Page", "description": "about it",
                                  "group": "Hardware", "status": "draft"})

    def test_quotes_stripped_and_trailing_comment_dropped(self):
        fields = read_scalars('---\ntitle: "Quoted: Title"\ngroup: Hardware   # the heading\n---\n')
        self.assertEqual(fields, {"title": "Quoted: Title", "group": "Hardware"})

    def test_key_followed_by_nested_block_reads_as_absent(self):
        fields = read_scalars("---\ntitle: A\ndescription:\n  - not a scalar\n---\n")
        self.assertEqual(fields, {"title": "A"})

    def test_frontmatter_without_trailing_newline_is_read(self):
        self.assertEqual(read_scalars("---\ntitle: A\n---"), {"title": "A"})


class TestLoadEntries(unittest.TestCase):
    def test_one_entry_per_page_sorted_by_filename(self):
        lore = make_lore({"B.md": page("B", "G2"), "A.md": page("A", "G1", status="deprecated")})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, [])
        self.assertEqual(entries, [
            {"file": "wiki/A.md", "title": "A", "hook": "about A", "group": "G1", "deprecated": True},
            {"file": "wiki/B.md", "title": "B", "hook": "about B", "group": "G2", "deprecated": False},
        ])

    def test_page_without_frontmatter_is_kept_with_a_warning(self):
        lore = make_lore({"Old_Note.md": page("Old Note", frontmatter=False)})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/Old_Note.md"])
        self.assertEqual(entries[0], {"file": "wiki/Old_Note.md", "title": "Old Note", "hook": "",
                                      "group": None, "deprecated": False})

    def test_page_with_frontmatter_but_no_title_warns_and_uses_filename(self):
        lore = make_lore({"No_Title.md": "---\ntype: concept\ndescription: d\n---\n"})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/No_Title.md"])
        self.assertEqual((entries[0]["title"], entries[0]["hook"]), ("No Title", "d"))

    def test_constants(self):
        self.assertEqual((UNGROUPED, DEPRECATED, ENTRY_CAP), ("Ungrouped", "Deprecated", 200))
        self.assertTrue(MARKER.startswith("<!-- generated by lore_index.py"))


if __name__ == "__main__":
    unittest.main()
