"""Tests for scripts/lore_index.py — run with: python3 -m unittest discover scripts"""
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import lore_index
from lore_index import DEPRECATED, ENTRY_CAP, MARKER, UNGROUPED, load_entries, read_scalars

SCRIPT = Path(__file__).resolve().parent / "lore_index.py"


def page(title, group=None, description=None, status=None, frontmatter=True):
    """A minimal wiki page. description=None -> 'about <title>'."""
    if not frontmatter:
        return f"# {title}\n\nbody\n"
    lines = ["---", "type: concept", f"title: {title}",
             f"description: {description if description is not None else 'about ' + title}"]
    if group:
        lines.append(f"group: {group}")
    lines += ["tags: [x]", "generated:", "  by: lore/test", "  at: 2026-08-01"]
    if status:
        lines.append(f"status: {status}")
    return "\n".join(lines) + "\n---\n\nbody\n"


def make_lore(pages=None, index_text=None):
    """A lore with wiki/, raw/, CLAUDE.md and the given wiki pages (name -> text)."""
    root = Path(tempfile.mkdtemp())
    (root / "wiki").mkdir()
    (root / "raw").mkdir()
    (root / "CLAUDE.md").write_text("# schema\n")
    for name, text in (pages or {}).items():
        (root / "wiki" / name).write_text(text)
    if index_text is not None:
        (root / "index.md").write_text(index_text)
    return root


def run(lore, *flags):
    return subprocess.run([sys.executable, str(SCRIPT), str(lore), *flags],
                          capture_output=True, text=True)


class TestReadScalars(unittest.TestCase):
    def test_no_frontmatter_is_none(self):
        self.assertIsNone(read_scalars("# Just a heading\n\ntext\n"))

    def test_top_level_scalars_only(self):
        fields = read_scalars("---\ntype: concept\ntitle: A Page\ndescription: about it\n"
                              "group: Hardware\nstatus: draft\ntags: [x]\n"
                              "generated:\n  by: lore/test\n  at: 2026-08-01\n---\nbody\n")
        self.assertEqual(fields, {"title": "A Page", "description": "about it",
                                  "group": "Hardware", "status": "draft"})

    def test_quotes_stripped_and_trailing_comment_dropped(self):
        fields = read_scalars('---\ntitle: "Quoted: Title"\ngroup: Hardware   # the heading\n---\n')
        self.assertEqual(fields, {"title": "Quoted: Title", "group": "Hardware"})

    def test_key_followed_by_nested_block_reads_as_absent(self):
        fields = read_scalars("---\ntitle: A\ndescription:\n  - not a scalar\n---\n")
        self.assertEqual(fields, {"title": "A"})

    def test_frontmatter_without_trailing_newline_is_read(self):
        self.assertEqual(read_scalars("---\ntitle: A\n---"), {"title": "A"})


class TestLoadEntries(unittest.TestCase):
    def test_one_entry_per_page_sorted_by_filename(self):
        lore = make_lore({"B.md": page("B", "G2"), "A.md": page("A", "G1", status="deprecated")})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, [])
        self.assertEqual(entries, [
            {"file": "wiki/A.md", "title": "A", "hook": "about A", "group": "G1", "deprecated": True},
            {"file": "wiki/B.md", "title": "B", "hook": "about B", "group": "G2", "deprecated": False},
        ])

    def test_page_without_frontmatter_is_kept_with_a_warning(self):
        lore = make_lore({"Old_Note.md": page("Old Note", frontmatter=False)})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/Old_Note.md"])
        self.assertEqual(entries[0], {"file": "wiki/Old_Note.md", "title": "Old Note", "hook": "",
                                      "group": None, "deprecated": False})

    def test_page_with_frontmatter_but_no_title_warns_and_uses_filename(self):
        lore = make_lore({"No_Title.md": "---\ntype: concept\ndescription: d\n---\n"})
        entries, warnings = load_entries(lore)
        self.assertEqual(warnings, ["WARN: no frontmatter wiki/No_Title.md"])
        self.assertEqual((entries[0]["title"], entries[0]["hook"]), ("No Title", "d"))

    def test_constants(self):
        self.assertEqual((UNGROUPED, DEPRECATED, ENTRY_CAP), ("Ungrouped", "Deprecated", 200))
        self.assertTrue(MARKER.startswith("<!-- generated by lore_index.py"))


from lore_index import entry_line, group_entries, render, render_flat, write_files  # noqa: E402


class TestGrouping(unittest.TestCase):
    def test_headings_sorted_case_insensitively_with_ungrouped_and_deprecated_last(self):
        lore = make_lore({
            "A.md": page("A", "zeta"), "B.md": page("B", "Alpha"), "C.md": page("C"),
            "D.md": page("D", "Alpha", status="deprecated"), "E.md": page("E", "Beta"),
        })
        entries, _ = load_entries(lore)
        headings = [h for h, _ in group_entries(entries)]
        self.assertEqual(headings, ["Alpha", "Beta", "zeta", "Ungrouped", "Deprecated"])

    def test_entries_sorted_by_title_case_insensitively(self):
        lore = make_lore({"1.md": page("beta", "G"), "2.md": page("Alpha", "G"), "3.md": page("Gamma", "G")})
        entries, _ = load_entries(lore)
        self.assertEqual([e["title"] for e in group_entries(entries)[0][1]], ["Alpha", "beta", "Gamma"])

    def test_deprecated_wins_over_group(self):
        lore = make_lore({"A.md": page("A", "Hardware", status="deprecated")})
        entries, _ = load_entries(lore)
        self.assertEqual(group_entries(entries), [("Deprecated", entries)])


class TestEntryLine(unittest.TestCase):
    def test_line_is_title_link_and_description(self):
        line, warning = entry_line({"file": "wiki/A_Page.md", "title": "A Page", "hook": "the hook",
                                    "group": "G", "deprecated": False})
        self.assertEqual(line, "- [A Page](wiki/A_Page.md) — the hook")
        self.assertIsNone(warning)

    def test_empty_hook_has_no_dash(self):
        line, _ = entry_line({"file": "wiki/A.md", "title": "A", "hook": "", "group": None, "deprecated": False})
        self.assertEqual(line, "- [A](wiki/A.md)")

    def test_over_cap_hook_is_cut_at_a_word_boundary_with_ellipsis_and_warning(self):
        entry = {"file": "wiki/A.md", "title": "A", "hook": "word " * 60, "group": "G", "deprecated": False}
        line, warning = entry_line(entry)
        self.assertLess(len(line), ENTRY_CAP)
        self.assertTrue(line.endswith("…"))
        self.assertEqual(line[:-1].split(" ")[-1], "word")          # no partial word before the ellipsis
        self.assertEqual(warning, f"WARN: over-cap wiki/A.md ({len('- [A](wiki/A.md) — ' + 'word ' * 60)} chars)")

    def test_line_of_exactly_199_chars_is_not_cut(self):
        hook = "x" * (199 - len("- [A](wiki/A.md) — "))
        line, warning = entry_line({"file": "wiki/A.md", "title": "A", "hook": hook, "group": "G", "deprecated": False})
        self.assertEqual((len(line), warning), (199, None))

    def test_prefix_alone_over_cap_cuts_the_title_not_the_link(self):
        entry = {"file": "wiki/A.md", "title": "T" * 190, "hook": "x", "group": "G", "deprecated": False}
        naive = f"- [{entry['title']}](wiki/A.md) — x"
        line, warning = entry_line(entry)
        self.assertLess(len(line), ENTRY_CAP)
        self.assertTrue(line.endswith("…](wiki/A.md)"))              # link target intact
        self.assertEqual(warning, f"WARN: over-cap wiki/A.md ({len(naive)} chars)")

    def test_pathological_long_filename_is_emitted_as_is_with_warning(self):
        long_file = "wiki/" + "f" * 250 + ".md"
        entry = {"file": long_file, "title": "T", "hook": "x", "group": "G", "deprecated": False}
        naive = f"- [T]({long_file}) — x"
        line, warning = entry_line(entry)
        self.assertEqual(line, naive)                                 # not truncated: cap can't be met
        self.assertEqual(warning, f"WARN: over-cap {long_file} ({len(naive)} chars)")


class TestRenderFlat(unittest.TestCase):
    def test_layout(self):
        lore = make_lore({"B.md": page("B", "Hardware"), "A.md": page("A", "Hardware"),
                          "N.md": page("N", frontmatter=False), "D.md": page("D", "Hardware", status="deprecated")})
        files, messages = render(lore)
        self.assertEqual(list(files), ["index.md"])
        self.assertEqual(files["index.md"], "\n".join([
            "# Lore Index", MARKER, "",
            "## Hardware",
            "- [A](wiki/A.md) — about A",
            "- [B](wiki/B.md) — about B",
            "",
            "## Ungrouped",
            "- [N](wiki/N.md)",
            "",
            "## Deprecated",
            "- [D](wiki/D.md) — about D",
        ]) + "\n")
        self.assertEqual(messages, ["WARN: no frontmatter wiki/N.md"])

    def test_empty_wiki_renders_header_only(self):
        files, messages = render(make_lore())
        self.assertEqual((files["index.md"], messages), (f"# Lore Index\n{MARKER}\n", []))

    def test_over_cap_warning_is_reported(self):
        lore = make_lore({"A.md": page("A", "G", description="word " * 60)})
        _, messages = render(lore)
        self.assertEqual(len(messages), 1)
        self.assertTrue(messages[0].startswith("WARN: over-cap wiki/A.md ("))


class TestCli(unittest.TestCase):
    def test_writes_index_md_and_exits_0(self):
        lore = make_lore({"A.md": page("A", "G")})
        proc = run(lore)
        self.assertEqual((proc.returncode, proc.stdout, proc.stderr), (0, "", ""))
        self.assertEqual((lore / "index.md").read_text(), f"# Lore Index\n{MARKER}\n\n## G\n- [A](wiki/A.md) — about A\n")

    def test_warnings_go_to_stdout(self):
        lore = make_lore({"N.md": page("N", frontmatter=False)})
        proc = run(lore)
        self.assertEqual((proc.returncode, proc.stdout), (0, "WARN: no frontmatter wiki/N.md\n"))

    def test_second_run_is_byte_identical(self):
        lore = make_lore({"A.md": page("A", "G"), "B.md": page("B", "H")})
        run(lore)
        first = (lore / "index.md").read_bytes()
        run(lore)
        self.assertEqual((lore / "index.md").read_bytes(), first)

    def test_not_a_lore_exits_2_and_writes_nothing(self):
        root = Path(tempfile.mkdtemp())
        proc = run(root)
        self.assertEqual(proc.returncode, 2)
        self.assertIn("ERROR:", proc.stderr)
        self.assertFalse((root / "index.md").exists())

    def test_lore_needs_claude_md_not_index_md(self):
        lore = make_lore({"A.md": page("A", "G")})
        (lore / "CLAUDE.md").unlink()
        self.assertEqual(run(lore).returncode, 2)


from lore_index import check, list_groups  # noqa: E402


class TestGroupsFlag(unittest.TestCase):
    def test_lists_group_values_with_counts_including_deprecated_pages(self):
        lore = make_lore({"A.md": page("A", "zeta"), "B.md": page("B", "Alpha"),
                          "C.md": page("C", "Alpha", status="deprecated"), "N.md": page("N")})
        entries, _ = load_entries(lore)
        self.assertEqual(list_groups(entries), [("Alpha", 2), ("zeta", 1), ("Ungrouped", 1)])
        proc = run(lore, "--groups")
        self.assertEqual((proc.returncode, proc.stdout), (0, "Alpha\t2\nzeta\t1\nUngrouped\t1\n"))
        self.assertFalse((lore / "index.md").exists())          # --groups never writes

    def test_a_page_with_literal_group_deprecated_sorts_like_its_heading(self):
        # group_entries buckets a page whose frontmatter literally sets
        # group: Deprecated under "## Deprecated" (heading_for returns the
        # group verbatim for a non-deprecated page); --groups must order it
        # the same way, not alphabetically among ordinary groups.
        lore = make_lore({"A.md": page("A", "Deprecated"), "B.md": page("B", "Alpha")})
        entries, _ = load_entries(lore)
        self.assertEqual(list_groups(entries), [("Alpha", 1), ("Deprecated", 1)])
        self.assertEqual([h for h, _ in group_entries(entries)], ["Alpha", "Deprecated"])


class TestCheckFlag(unittest.TestCase):
    def test_fresh_index_is_not_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        run(lore)
        self.assertEqual(check(lore), [])
        proc = run(lore, "--check")
        self.assertEqual((proc.returncode, proc.stdout), (0, ""))

    def test_new_page_without_regeneration_is_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        run(lore)
        (lore / "wiki" / "B.md").write_text(page("B", "G"))
        self.assertEqual(check(lore), ["index.md"])
        proc = run(lore, "--check")
        self.assertEqual((proc.returncode, proc.stdout), (1, "DRIFT index.md\n"))
        self.assertNotIn("B", (lore / "index.md").read_text())   # --check never writes

    def test_missing_index_is_drift(self):
        lore = make_lore({"A.md": page("A", "G")})
        self.assertEqual(check(lore), ["index.md"])


if __name__ == "__main__":
    unittest.main()
